Repository pagesource/atomic-react-components, pull requests merged in 2019-11, with the labels that each got.

#110 Issue 53/husky config
  commitLint.config.js
  package.json
Labels: maintenance

#108 Maintenance/storybook jest and figma integration
  .jest-test-results.json
  .storybook/addons.js
  .storybook/config.js
  config/jest.config.js
  generators/component/story.js.hbs
  lib/components/atoms/Anchor/Anchor.story.js
  lib/components/atoms/Button/Button.story.js
  lib/components/atoms/FieldError/FieldError.story.js
  lib/components/atoms/Heading/Heading.story.js
  lib/components/atoms/Image/Image.story.js
  lib/components/atoms/Input/Input.story.js
  lib/components/atoms/Label/Label.story.js
  lib/components/atoms/Para/Para.story.js
  lib/components/atoms/Select/Select.story.js
  lib/components/atoms/Textarea/Textarea.story.js
  lib/components/molecules/ArticleThumbnail/ArticleThumbnail.story.js
  lib/components/molecules/Breadcrumb/Breadcrumb.story.js
  lib/components/molecules/Form/FieldTextarea/FieldTextarea.story.js
  lib/components/molecules/Form/Form.story.js
  lib/components/molecules/InputChoice/InputChoice.story.js
  lib/components/molecules/List/List.story.js
  lib/components/molecules/Modal/Modal.story.js
  lib/components/molecules/Popover/Popover.story.js
  lib/components/molecules/Tabs/Tab/Tab.story.js
  lib/components/molecules/Tabs/TabPanel/TabPanel.story.js
  lib/components/molecules/Tabs/Tabs.story.js
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement, maintenance

#116 issue-72 | updated class name for hoc
  generators/component/hoc.js.hbs
Labels: bug
